# Created using wingetcreate 1.5.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: jmeubank.TDM-GCC
PackageVersion: 10.3.0
PackageLocale: en-US
Publisher: jmeubank
PackageName: TDM-GCC
License: CC0 Creative Commons License
ShortDescription: TDM-GCC is a cleverly disguised GCC compiler for Windows!
ManifestType: defaultLocale
ManifestVersion: 1.5.0
