# Created using wingetcreate

PackageIdentifier: IDRIX.VeraCrypt
PackageVersion: 1.24-Update7
PackageLocale: en-US
Publisher: IDRIX
PackageName: VeraCrypt
License: Apache License
ShortDescription: Disk encryption with strong security based on TrueCrypt
ManifestType: defaultLocale
ManifestVersion: 1.0.0
