# Created using wingetcreate

PackageIdentifier: jmeubank.TDM-GCC
PackageVersion: 1.2105.1
PackageLocale: en-US
Publisher: jmeubank
PackageName: TDM-GCC
License: CC0 Creative Commons License
ShortDescription: TDM-GCC is a cleverly disguised GCC compiler for Windows!
ManifestType: defaultLocale
ManifestVersion: 1.0.0
